[package]
name = "aoch"
version = "0.3.0"
authors = ["Chris Moore"]
edition = "2018"
description = "A helper crate + commands to assist with the annual Advent of Code (AoC) competition"
homepage = "https://github.com/csm123199/aochelper"
repository = "https://github.com/csm123199/aochelper"
readme = "README.md"
license = "SimPL-2.0"
keywords = ["aoc", "advent-of-code", "programming-puzzles"]
categories = ["development-tools", "development-tools::cargo-plugins"]


[dependencies]
clap = "3.0.0-beta.2"
toml_edit = "0.2.0"

# Can use public once/if https://github.com/killercup/cargo-edit/pull/437 gets merged
cargo-edit = { git = "https://github.com/csm123199/cargo-edit" }

# helper stuff
colored = "1.9.0"
ptree = "0.2.1"
atty = "0.2.13"
