[package]
name = "aochelper"
version = "0.1.0"
authors = ["Chris Moore"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9.0"
ptree = "0.2.1"
atty = "0.2.13"
