
# cargo-features = ["edition2021"]

[package]
name = "aoch-proc"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.99"
quote = "1.0.21"
proc-macro2 = "1.0.43"

[lib]
proc-macro = true

