
# cargo-features = ["edition2021"]

[package]
name = "aoch-proc"
version = "0.2.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "2.0.39"
quote = "1.0.33"
proc-macro2 = "1.0.70"

[lib]
proc-macro = true

